# Generated by Django 4.0.5 on 2022-06-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=10)),
                ('capacidad', models.SmallIntegerField()),
                ('compañia', models.CharField(max_length=255)),
            ],
        ),
    ]
