# Generated by Django 4.0.4 on 2022-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=120)),
                ('telefono', models.CharField(max_length=80)),
            ],
        ),
    ]
