# Generated by Django 4.0.5 on 2022-06-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
            ],
        ),
    ]
