# Generated by Django 4.0.4 on 2022-06-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasajeros', '0002_alter_pasajero_cedula_alter_pasajero_correo'),
        ('rutas', '0001_initial'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiquetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_viaje', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('pasajero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajeros.pasajero')),
                ('ruta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
            ],
        ),
    ]
