# Generated by Django 4.0.5 on 2022-06-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiquetes',
            old_name='bus_id',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='tiquetes',
            old_name='pasajero_id',
            new_name='pasajero',
        ),
        migrations.RenameField(
            model_name='tiquetes',
            old_name='ruta_id',
            new_name='ruta',
        ),
    ]
